version: "3.9"

services:
  db:
    image: postgres:15
    container_name: datapulse_db
    environment:
      POSTGRES_USER: datapulse
      POSTGRES_PASSWORD: datapulse
      POSTGRES_DB: datapulse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./backend
    container_name: datapulse_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=datapulse
      - DB_USER=datapulse
      - DB_PASSWORD=datapulse
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
