services:
  db:
    image: postgres:15
    container_name: core_db
    environment:
      POSTGRES_USER: core
      POSTGRES_PASSWORD: core
      POSTGRES_DB: core
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: core_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=core
      - DB_USER=core
      - DB_PASSWORD=core
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=1
      - SECRET_KEY=your-secret-key-for-development

  test:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: core_test
    command: python manage.py test --settings=core.test_settings -v 2
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=test-secret-key
      - DEBUG=1
      - DB_PASSWORD=core
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
