services:
  - type: web
    name: core-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    buildFilter:
      paths:
        - backend/**/*
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SUPERUSER_EMAIL
        value: "tassio72@hotmail.com"
      - key: SUPERUSER_NAME
        value: "Admin User"
      - key: SUPERUSER_PASSWORD
        generateValue: true
      - key: DB_NAME
        fromDatabase:
          name: core-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: core-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: core-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: core-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: core-db
          property: port
databases:
  - name: core-db
    plan: free
