# Generated by Django 5.2.3 on 2025-06-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, help_text='Password for user authentication (optional for now)', max_length=128, null=True),
        ),
    ]
