# Generated by Django 5.2.3 on 2025-07-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'admin'), ('owner', 'owner'), ('member', 'member')], default='member', max_length=20),
        ),
    ]
