# Generated by Django 5.2.3 on 2025-06-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('superuser', 'Superuser'), ('developer', 'Developer')], default='developer', max_length=20),
        ),
    ]
